name: Build and Release
on:
    push:
        branches: [main]

permissions:
    contents: write

jobs:
    build_and_release:
        runs-on: ${{ matrix.os }}
        env: 
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v1
              with:
                  node-version: 18
            - name: Linux Build
              if: matrix.os == 'ubuntu-latest'

              run: |
                sudo snap install snapcraft --classic
                wget "https://github.com/yt-dlp/FFmpeg-Builds/releases/latest/download/ffmpeg-n6.0-latest-linux64-gpl-6.0.tar.xz"
                tar xvf ffmpeg-n6.0-latest-linux64-gpl-6.0.tar.xz
                cp ffmpeg-n6.0-latest-linux64-gpl-6.0/bin/ffmpeg ffmpeg
                chmod +x ffmpeg
                rm -rf ffmpeg-n6.0-latest-linux64-gpl-6.0
                rm ffmpeg-n6.0-latest-linux64-gpl-6.0.tar.xz
                npx electron-builder -l --publish=always
            
            - name: Macos Build
              if: matrix.os == 'macos-latest'
              run: |
                wget "https://github.com/yt-dlp/FFmpeg-Builds/releases/latest/download/ffmpeg-n6.0-latest-linux64-gpl-6.0.tar.xz"
                tar xvf ffmpeg-n6.0-latest-linux64-gpl-6.0.tar.xz
                cp ffmpeg-n6.0-latest-linux64-gpl-6.0/bin/ffmpeg ffmpeg
                chmod +x ffmpeg
                rm -rf ffmpeg-n6.0-latest-linux64-gpl-6.0
                rm ffmpeg-n6.0-latest-linux64-gpl-6.0.tar.xz
                npx electron-builder -m --publish=always
            
            - name: Windows Build
              if: matrix.os == 'windows-latest'
              run: |
                curl -LOk "https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-n6.0-latest-win64-gpl-6.0.zip"
                Expand-Archive ffmpeg-n6.0-latest-win64-gpl-6.0.zip
                Copy-Item ffmpeg-n6.0-latest-win64-gpl-6.0\bin\ffmpeg.exe ffmpeg.exe
                Remove-Item -Recurse -Force ffmpeg-n6.0-latest-win64-gpl-6.0
                Remove-Item -Force ffmpeg-n6.0-latest-win64-gpl-6.0.zip
                npx electron-builder -w --publish=always
            # - name: Upload Artifacts
            #   id: upload-artifacts
            #   uses: softprops/action-gh-release@v1
            #   with:
            #       files: |
            #           tgpt-linux-amd64
            #           tgpt-linux-i386
            #           tgpt-linux-arm64
            #           tgpt-amd64.exe
            #           tgpt-i386.exe
            #           tgpt-mac-amd64
            #           tgpt-mac-arm64
            #       token: ${{ secrets.GITHUB_TOKEN }}
            #       draft: true
            #       tag_name: v
            #       name: tgpt
